apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      initContainers:
        - name: wait-for-postgresql
          image: busybox
          command: 
            - sh
            - -c
            - |
              until nc -z {{ .Release.Name }}-postgresql {{ .Values.postgresql.service.port }}; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 2
              done
      volumes:
        - name: kube-config
          hostPath:
            path: /root/.kube
            type: Directory
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          # command: ["uvicorn"]
          # args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              name: http
          volumeMounts:
            - name: kube-config
              mountPath: /root/.kube
              readOnly: true
          env:
            - name: PROJECT_NAME
              value: {{ .Values.global.projectName | quote }}
            - name: DOMAIN
              value: {{ .Values.global.domain | quote }}
            - name: FRONTEND_HOST
              value: {{ .Values.backend.env.FRONTEND_HOST | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.global.environment | quote }}
            - name: BACKEND_CORS_ORIGINS
              value: {{ .Values.backend.env.BACKEND_CORS_ORIGINS | quote }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-backend-secrets
                  key: SECRET_KEY
            - name: FIRST_SUPERUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-backend-secrets
                  key: FIRST_SUPERUSER
            - name: FIRST_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-backend-secrets
                  key: FIRST_SUPERUSER_PASSWORD
            - name: POSTGRES_SERVER
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.service.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgres-password
            - name: SMTP_HOST
              value: {{ .Values.backend.env.SMTP_HOST | quote }}
            - name: SMTP_PORT
              value: {{ .Values.backend.env.SMTP_PORT | quote }}
            - name: SMTP_TLS
              value: {{ .Values.backend.env.SMTP_TLS | quote }}
            - name: EMAILS_FROM_EMAIL
              value: {{ .Values.backend.env.EMAILS_FROM_EMAIL | quote }}
            - name: KUBECONFIG
              value: "/root/.kube/config"
            - name: FINETUNE_IMAGE
              value: {{ .Values.backend.env.FINETUNE_IMAGE | quote }}
            - name: FINETUNE_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: MAX_CONCURRENT_TASKS
              value: {{ .Values.backend.env.MAX_CONCURRENT_TASKS | quote }}
            - name: MAX_TASKS_PER_USER
              value: {{ .Values.backend.env.MAX_TASKS_PER_USER | quote }}
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi 