{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: {{ .service.port }}
          env:
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
{{- end -}}

---
# Backend Deployment
{{- with .Values.backend -}}
{{- include "common.deployment" . }}
---
{{- end }}

# Frontend Deployment  
{{- with .Values.frontend -}}
{{- include "common.deployment" . }}
---
{{- end }}

# Adminer Deployment
{{- if .Values.adminer.enabled -}}
{{- with .Values.adminer -}}
{{- include "common.deployment" . }}
---
{{- end }}
{{- end }}

# Mailcatcher Deployment
{{- if .Values.mailcatcher.enabled -}}
{{- with .Values.mailcatcher -}}
{{- include "common.deployment" . }}
{{- end }}
{{- end }} 