apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
  labels:
    app.kubernetes.io/name: backend-secrets
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.backend.secrets.secretKey | b64enc | quote }}
  FIRST_SUPERUSER: {{ .Values.backend.secrets.firstSuperuser | b64enc | quote }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.backend.secrets.firstSuperuserPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }} 