apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: web
      protocol: TCP
      name: web
    - port: 443
      targetPort: websecure
      protocol: TCP
      name: websecure
    - port: 8080
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: {{ .Release.Name }} 