# 全局配置
global:
  projectName: slmflow
  environment: local
  domain: localhost.tiangolo.com

# PostgreSQL配置
postgresql:
  auth:
    username: postgres
    password: changethis
    database: app
  service:
    port: 5432
  persistence:
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Traefik配置  
traefik:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  additionalArguments:
    - "--log.level=DEBUG"
    - "--api.insecure=true"
    - "--providers.kubernetesingress.ingressclass=traefik"
    - "--accesslog=true"

# 后端服务配置
backend:
  replicaCount: 1
  image:
    repository: backend
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    FRONTEND_HOST: "http://dashboard.localhost.tiangolo.com"
    BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173,http://localhost:3000,http://localhost:8080,http://dashboard.localhost.tiangolo.com"
    SMTP_HOST: mailcatcher
    SMTP_PORT: "1025"
    SMTP_TLS: "false"
    EMAILS_FROM_EMAIL: "noreply@example.com"
    FINETUNE_IMAGE: "your-finetune-image:latest"
    MAX_CONCURRENT_TASKS: "5"
    MAX_TASKS_PER_USER: "3"
  service:
    type: NodePort
    port: 8000
    nodePort: 30080
  secrets:
    secretKey: "changethis"
    firstSuperuser: "admin@example.com"
    firstSuperuserPassword: "changethis"

# 前端服务配置    
frontend:
  replicaCount: 1
  image:
    repository: frontend
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    NODE_ENV: development
  service:
    type: NodePort
    port: 80
    nodePort: 30081

# Adminer配置
adminer:
  enabled: true
  image:
    repository: adminer
    tag: latest
    pullPolicy: IfNotPresent
  env:
    ADMINER_DESIGN: pepa-linha-dark
  service:
    type: ClusterIP
    port: 8080

# Mailcatcher配置
mailcatcher:
  enabled: true
  image:
    repository: schickling/mailcatcher
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    ports:
      - name: web
        port: 1080
      - name: smtp
        port: 1025 